# Docker-compose.yml is for already created/build images by docker/community which can directly by pulled manually/indirectly by docker
# Dockerfile is for building my own application and converting it into an image

version: "3.8"
# Compose file format version

services:
  # each individual service is a container
  minio:    # minio container
    image: minio/minio       # get the image from dockerHub (docker pulls it  if not present in the system already)
    container_name: minio
    ports:
      - "9000:9000"      # localhostport:dokcerport  for the API(S3)
      - "9001:9001"      # for the console(GUI)
    environment:
      # info for the environment used by the container (minio here) (other ex: MYSQL_ROOT_USERNAME, MYSQL_ROOT_DB (database name))
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"    # command to start the container
    # Start minio server store minio objects in /data and have the console address at port 9001
    # these are the commands needed by minio to get started
    volumes:
      - minio_data:/data
        #store the minio_data at /data
      # So when MinIO writes files to /data, they go into minio_data.
      # minio_data (Docker-managed storage)
      #            ↓
      # mapped to /data inside container where the data is saved by minIO
volumes:
  minio_data:
  #declaration of volume for docker to manage the data
  # why is volumes coming two times
  # one is for declaring it inside the service (for minIO)
  # another one is to tell docker to save the volumes in minio_data

#You see there are two things happening in here minIO is storing the data at /data
# whereas it is managed by/stored by docker whole as a volume